import { defineField, defineType } from 'sanity';
import { Settings } from 'lucide-react';

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Website Settings',
  type: 'document',
  icon: Settings,
  groups: [
    { name: 'general', title: 'Website Basics', default: true },
    { name: 'announcement', title: 'Announcement Banner' },
    { name: 'contact', title: 'Contact Information' },
    { name: 'social', title: 'Social Media Links' },
    { name: 'booking', title: 'Booking Page & FAQs' },
    { name: 'pageHeaders', title: 'Page Banners & Headers' },
    { name: 'sharing', title: 'Sharing & Search' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Website Title',
      type: 'string',
      group: 'general',
      description: 'Shown in browser tabs and when people search for your site on Google.',
      validation: (Rule) => Rule.required(),
      initialValue: 'Grains of Time | NC State All-Male A Cappella',
    }),
    defineField({
      name: 'description',
      title: 'Website Description',
      type: 'text',
      rows: 3,
      group: 'general',
      description: 'A short description of your group. Google and social media use this when showing your site in search results. Keep it under 200 characters.',
      validation: (Rule) => Rule.required().max(200),
      initialValue: 'Official website and living archive of Grains of Time, North Carolina State University\'s premier all-male a cappella ensemble, founded in 1968.',
    }),
    defineField({
      name: 'foundedYear',
      title: 'Year Founded',
      type: 'number',
      group: 'general',
      readOnly: true,
      initialValue: 1968,
      description: 'The year Grains of Time was founded. This is shown on the website but cannot be changed.',
    }),
    defineField({
      name: 'locationAffiliation',
      title: 'University & Location',
      type: 'string',
      group: 'general',
      initialValue: 'North Carolina State University • Raleigh, North Carolina',
      description: 'Shown in the footer and on the homepage.',
    }),
    // Announcement Banner
    defineField({
      name: 'announcement',
      title: 'Announcement Banner',
      type: 'object',
      group: 'announcement',
      description: 'A colored bar at the top of every page. Use it for audition dates, ticket sales, or important news.',
      fields: [
        defineField({
          name: 'enabled',
          title: 'Show Banner',
          type: 'boolean',
          description: 'Turn this on to display the announcement on the website.',
          initialValue: false,
        }),
        defineField({
          name: 'text',
          title: 'Banner Message',
          type: 'string',
          description: 'Keep it short — e.g. "Fall Auditions: September 15 at Price Music Center"',
        }),
        defineField({
          name: 'linkUrl',
          title: 'Link (optional)',
          type: 'string',
          description: 'Where should the banner link to? Use a page on your site (e.g. /events) or a full web address.',
        }),
        defineField({
          name: 'linkText',
          title: 'Link Button Text',
          type: 'string',
          initialValue: 'Learn More',
          description: 'The clickable text at the end of the banner, e.g. "Learn More", "Get Tickets", "Sign Up".',
        }),
      ],
    }),
    // Contact
    defineField({
      name: 'contactEmail',
      title: 'General Contact Email',
      type: 'string',
      group: 'contact',
      validation: (Rule) => Rule.email(),
      initialValue: 'ncstategrains@gmail.com',
      description: 'The main email address shown on the website for general inquiries.',
    }),
    defineField({
      name: 'bookingEmail',
      title: 'Booking Email',
      type: 'string',
      group: 'contact',
      validation: (Rule) => Rule.email(),
      initialValue: 'booking@grainsoftime.org',
      description: 'The email address where booking/performance requests are sent.',
    }),
    // Social Media
    defineField({
      name: 'socialLinks',
      title: 'Social Media Links',
      type: 'object',
      group: 'social',
      description: 'Add your official social media profiles. Leave any field empty to hide that icon on the website.',
      fields: [
        defineField({
          name: 'instagram',
          title: 'Instagram',
          type: 'url',
          description: 'Your Instagram profile URL (e.g. https://instagram.com/grainsoftime)',
          initialValue: 'https://instagram.com/grainsoftime',
        }),
        defineField({
          name: 'spotify',
          title: 'Spotify',
          type: 'url',
          description: 'Your Spotify artist page URL. Leave empty if you don\'t have one yet.',
        }),
        defineField({
          name: 'appleMusic',
          title: 'Apple Music',
          type: 'url',
          description: 'Your Apple Music artist page URL.',
          initialValue: 'https://music.apple.com/us/artist/grains-of-time/213326965',
        }),
        defineField({
          name: 'tiktok',
          title: 'TikTok',
          type: 'url',
          description: 'Your TikTok profile URL.',
          initialValue: 'https://www.tiktok.com/@grainsoftime?is_from_webapp=1&sender_device=pc',
        }),
        defineField({
          name: 'youtube',
          title: 'YouTube',
          type: 'url',
          description: 'Your YouTube channel URL. Leave empty if you don\'t have one yet.',
        }),
        defineField({
          name: 'facebook',
          title: 'Facebook',
          type: 'url',
          description: 'Your Facebook profile/page URL. Leave empty if you don\'t have one yet.',
          initialValue: 'https://www.facebook.com/grainsoftime/',
        }),
        defineField({
          name: 'gofundme',
          title: 'Fundraising / Support Page',
          type: 'url',
          description: 'GoFundMe or other fundraising page URL. Leave empty when not running a campaign.',
        }),
        defineField({
          name: 'merch',
          title: 'Merchandise Store',
          type: 'url',
          description: 'Your online merchandise store URL.',
          initialValue: 'https://ladiesinredncsu.myshopify.com/collections/all',
          validation: (Rule) => Rule.required(),
        }),
      ],
    }),
    // Sharing
    defineField({
      name: 'defaultOgImage',
      title: 'Social Media Preview Image',
      type: 'image',
      group: 'sharing',
      options: { hotspot: true },
      description: 'When someone shares your website on social media or in a text message, this image is shown as the preview. Use a high-quality group photo (recommended size: 1200×630 pixels).',
      fields: [
        defineField({
          name: 'alt',
          title: 'Describe This Image',
          type: 'string',
          validation: (Rule) => Rule.required(),
        }),
      ],
    }),
    // Booking Page Configuration
    defineField({
      name: 'bookingHeading',
      title: 'Booking Page Heading',
      type: 'string',
      group: 'booking',
      initialValue: 'Bring the Sound to Your Event',
    }),
    defineField({
      name: 'bookingSubtitle',
      title: 'Booking Page Subtitle',
      type: 'text',
      rows: 2,
      group: 'booking',
      initialValue: 'From NC State university convocations to private celebrations and masterclasses, Grains of Time brings unforgettable vocal energy to every stage.',
    }),
    defineField({
      name: 'bookingGuidelines',
      title: 'Technical Guidelines & Requirements',
      type: 'array',
      group: 'booking',
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'title',
              title: 'Guideline Title',
              type: 'string',
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: 'description',
              title: 'Description',
              type: 'text',
              rows: 3,
              validation: (Rule) => Rule.required(),
            }),
          ],
        },
      ],
    }),
    defineField({
      name: 'bookingFaqs',
      title: 'Frequently Asked Questions',
      type: 'array',
      group: 'booking',
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'q',
              title: 'Question',
              type: 'string',
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: 'a',
              title: 'Answer',
              type: 'text',
              rows: 3,
              validation: (Rule) => Rule.required(),
            }),
          ],
        },
      ],
    }),

    // Page Banners & Headers
    defineField({
      name: 'rosterEyebrow',
      title: 'Roster Page Eyebrow',
      type: 'string',
      group: 'pageHeaders',
      initialValue: 'The Voices',
    }),
    defineField({
      name: 'rosterHeading',
      title: 'Roster Page Heading',
      type: 'string',
      group: 'pageHeaders',
      initialValue: 'Current Ensemble',
    }),
    defineField({
      name: 'rosterSubtitle',
      title: 'Roster Page Subtitle',
      type: 'text',
      rows: 2,
      group: 'pageHeaders',
      initialValue: 'Nine to fifteen undergraduate voices spanning five distinct vocal sections, performing without instrumental accompaniment.',
    }),
    defineField({
      name: 'rosterHeroImage',
      title: 'Ensemble Banner Photograph',
      type: 'image',
      group: 'pageHeaders',
      options: { hotspot: true },
      description: 'The wide ensemble banner at the top of the Members page.',
      fields: [
        defineField({
          name: 'alt',
          title: 'Image Description',
          type: 'string',
          initialValue: 'Grains of Time active ensemble at the NC State Memorial Belltower',
        }),
        defineField({
          name: 'credit',
          title: 'Photo Credit',
          type: 'string',
          initialValue: 'Grains of Time Media Day',
        }),
      ],
    }),
    defineField({
      name: 'timelineEyebrow',
      title: 'Timeline Page Eyebrow',
      type: 'string',
      group: 'pageHeaders',
      initialValue: 'Chronicle • 1968 to Present',
    }),
    defineField({
      name: 'timelineHeading',
      title: 'Timeline Page Heading',
      type: 'string',
      group: 'pageHeaders',
      initialValue: 'The Living Archive',
    }),
    defineField({
      name: 'timelineSubtitle',
      title: 'Timeline Page Subtitle',
      type: 'text',
      rows: 2,
      group: 'pageHeaders',
      initialValue: 'A chronological record of sound, milestones, and brotherhood at North Carolina State University.',
    }),
    defineField({
      name: 'timelineArchivalNotice',
      title: 'Timeline Archival Policy Notice',
      type: 'text',
      rows: 3,
      group: 'pageHeaders',
      initialValue: 'This timeline documents verified organizational milestones. Dates, narratives, and archival imagery are curated directly from NC State university archives and Grains of Time alumni records.',
    }),
  ],
});
